version: '3'

services:
  app:
    build: .
    volumes:
      - ./app/:/home/local/
    stdin_open: true
    tty: true
    # ports:
    #   - "8888:8888"
    # command: >
    #   sh -c '
    #     flutter pub get &&
    #     flutter run -d web-server --web-port=8888 --web-hostname=0.0.0.0
    #   '
